# Generated by Django 3.2.6 on 2021-09-02 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_phrase', models.CharField(max_length=1024)),
                ('email_field', models.EmailField(max_length=254)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '2 minutes'), (2, '10 minute'), (3, '30 minutes')], default=3)),
                ('aleat_created_time', models.DateTimeField(auto_now_add=True)),
                ('aleat_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alert Created')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last alert send at')),
            ],
        ),
    ]
