# Generated by Django 3.2.6 on 2021-09-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebayalert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertscheduler',
            old_name='status',
            new_name='interval',
        ),
    ]
