# Generated by Django 3.2.6 on 2021-09-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebayalert', '0002_rename_status_alertscheduler_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertscheduler',
            name='aleat_created_time',
        ),
    ]
