# Generated by Django 3.2.6 on 2021-09-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebayalert', '0003_remove_alertscheduler_aleat_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertscheduler',
            old_name='email_field',
            new_name='email_address',
        ),
    ]
