# Generated by Django 3.2.6 on 2021-09-08 05:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebayalert', '0005_alter_alertscheduler_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_info', models.TextField()),
                ('aleat_send_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alert Send At')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebayalert.alertscheduler')),
            ],
        ),
    ]
