# Generated by Django 3.2.6 on 2021-09-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebayalert', '0006_alertinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertinfo',
            old_name='aleat_send_at',
            new_name='alert_send_at',
        ),
    ]
