# Generated by Django 3.2.6 on 2021-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebayalert', '0008_auto_20210908_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
